const data = {
    newFlowers: [
        {
            id: 1,
            image: "https://telegra.ph/file/b83978b881291a6b8765d.png",
            title: "Red Tulips",
            price: "46 $",
            previousPrice: "60 $",
        },
        {
            id: 2,
            image: "https://telegra.ph/file/350e649852e6ccf4d3ea7.png",
            title: "White roses, 7pc.",
            price: "44 $",
        },
        {
            id: 3,
            image: "https://telegra.ph/file/1329c6b988c2da2cccc1f.png",
            title: "Bouqueet “Dream”",
            price: "53 $",
        },
        {
            id: 4,
            image: "https://telegra.ph/file/09cd77cb2c8fb3d7513be.png",
            title: "White lilies, 21 pc.",
            price: "70 $",
        },
        {
            id: 5,
            image: "https://telegra.ph/file/b83978b881291a6b8765d.png",
            title: "Red Tulips",
            price: "46 $",
            previousPrice: "60 $",
        },
        {
            id: 6,
            image: "https://telegra.ph/file/350e649852e6ccf4d3ea7.png",
            title: "White roses, 7pc.",
            price: "44 $",
        },
        {
            id: 7,
            image: "https://telegra.ph/file/1329c6b988c2da2cccc1f.png",
            title: "Bouqueet “Dream”",
            price: "53 $",
        },
        {
            id: 8,
            image: "https://telegra.ph/file/09cd77cb2c8fb3d7513be.png",
            title: "White lilies, 21 pc.",
            price: "70 $",
        },
    ],
    relevantFlowers: [
        {
            id: "9",
            image: "https://telegra.ph/file/be6784358178a3dca98f1.png",
            title: "Bouquet “Maya”",
            price: "52.50 $",
        },
        {
            id: "10",
            image: "https://telegra.ph/file/bbaac4c71107a937e63e3.png",
            title: "Red tulips, 25 pc.",
            price: "46 $",
        },
        {
            id: "11",
            image: "https://telegra.ph/file/d519221e181f84afbc2ec.png",
            title: "Pink roses, 15 pc.",
            price: "34 $",
        },
        {
            id: "12",
            image: "https://telegra.ph/file/94902e1eda8df90f45eda.png",
            title: "Bouquet “Sunny”",
            price: "38.20 $",
            previousPrice: "60 $",
        },
        {
            id: "13",
            image: "https://telegra.ph/file/be6784358178a3dca98f1.png",
            title: "Bouquet “Maya”",
            price: "52.50 $",
        },
        {
            id: "14",
            image: "https://telegra.ph/file/bbaac4c71107a937e63e3.png",
            title: "Red tulips, 25 pc.",
            price: "46 $",
        },
        {
            id: "15",
            image: "https://telegra.ph/file/d519221e181f84afbc2ec.png",
            title: "Pink roses, 15 pc.",
            price: "34 $",
        },
        {
            id: "16",
            image: "https://telegra.ph/file/94902e1eda8df90f45eda.png",
            title: "Bouquet “Sunny”",
            price: "38.20 $",
            previousPrice: "60 $",
        },
    ],
    allPlants: [
        {
            id: "17",
            image: "https://telegra.ph/file/4ce75c55e339a37a4f119.png",
            title: "Lavander",
            price: "10 $",
        },
        {
            id: "18",
            image: "https://telegra.ph/file/8c14c1d37ecfddec2aac3.png",
            title: "Lavander",
            price: "10 $",
        },
        {
            id: "19",
            image: "https://telegra.ph/file/4f952f51bf15f42497410.png",
            title: "Red rose, 5 pc.",
            price: "16.99 $",
        },
        {
            id: "20",
            image: "https://telegra.ph/file/0f9be206640a33786b170.png",
            title: "Bouquet “Spring”",
            price: "20 $",
            previousPrice: "25 $",
        },
        {
            id: "21",
            image: "https://telegra.ph/file/c65e8fff7c2633773e1bc.png",
            title: "Lavander",
            price: "10 $",
        },
        {
            id: "22",
            image: "https://telegra.ph/file/0137df65674b602372c02.png",
            title: "Lavander",
            price: "10 $",
        },
        {
            id: "23",
            image: "https://telegra.ph/file/09cd77cb2c8fb3d7513be.png",
            title: "White lilies, 21 pc.",
            price: "70 $",
        },
        {
            id: "24",
            image: "https://telegra.ph/file/1329c6b988c2da2cccc1f.png",
            title: "Bouqueet “Dream”",
            price: "53 $",
        },
        {
            id: "25",
            image: "https://telegra.ph/file/4ce75c55e339a37a4f119.png",
            title: "Lavander",
            price: "10 $",
        },
        {
            id: "26",
            image: "https://telegra.ph/file/8c14c1d37ecfddec2aac3.png",
            title: "Lavander",
            price: "10 $",
        },
        {
            id: "27",
            image: "https://telegra.ph/file/4f952f51bf15f42497410.png",
            title: "Red rose, 5 pc.",
            price: "16.99 $",
        },
        {
            id: "28",
            image: "https://telegra.ph/file/0f9be206640a33786b170.png",
            title: "Bouquet “Spring”",
            price: "20 $",
            previousPrice: "25 $",
        },
        {
            id: "29",
            image: "https://telegra.ph/file/c65e8fff7c2633773e1bc.png",
            title: "Lavander",
            price: "10 $",
        },
        {
            id: "30",
            image: "https://telegra.ph/file/0137df65674b602372c02.png",
            title: "Lavander",
            price: "10 $",
        },
        {
            id: "31",
            image: "https://telegra.ph/file/09cd77cb2c8fb3d7513be.png",
            title: "White lilies, 21 pc.",
            price: "70 $",
        },
        {
            id: "32",
            image: "https://telegra.ph/file/1329c6b988c2da2cccc1f.png",
            title: "Bouqueet “Dream”",
            price: "53 $",
        },
        {
            id: "33",
            image: "https://telegra.ph/file/4ce75c55e339a37a4f119.png",
            title: "Lavander",
            price: "10 $",
        },
        {
            id: "34",
            image: "https://telegra.ph/file/8c14c1d37ecfddec2aac3.png",
            title: "Lavander",
            price: "10 $",
        },
        {
            id: "35",
            image: "https://telegra.ph/file/4f952f51bf15f42497410.png",
            title: "Red rose, 5 pc.",
            price: "16.99 $",
        },
        {
            id: "36",
            image: "https://telegra.ph/file/0f9be206640a33786b170.png",
            title: "Bouquet “Spring”",
            price: "20 $",
            previousPrice: "25 $",
        },
        {
            id: "37",
            image: "https://telegra.ph/file/c65e8fff7c2633773e1bc.png",
            title: "Lavander",
            price: "10 $",
        },
        {
            id: "38",
            image: "https://telegra.ph/file/0137df65674b602372c02.png",
            title: "Lavander",
            price: "10 $",
        },
        {
            id: "39",
            image: "https://telegra.ph/file/09cd77cb2c8fb3d7513be.png",
            title: "White lilies, 21 pc.",
            price: "70 $",
        },
        {
            id: "40",
            image: "https://telegra.ph/file/1329c6b988c2da2cccc1f.png",
            title: "Bouqueet “Dream”",
            price: "53 $",
        },
    ],
};
export default data;
